[package]
name = "reset_dns"
version = "0.1.0"
edition = "2021"
authors = ["a.k.a neimsaci https://neimsaci.info <mail_me@neimsaci.info>"]

[dependencies]
rsdns = "0.13.0"
registry = "1.2.2"
clap = "3.1.18"
crossterm = "0.23.2"
rustyline-with-hint-fix = "9.1.4"